name: Trigger Repo A Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repo A
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_A_PAT }}
          repository: mynewproject0/RepoA
          event-type: trigger-event
